main: fr.hyriode.rushtheflag.HyriRTF

version: 0.0.1 SNAPSHOT

name: HyriRushTheFlag

author: Calyx

commands:
  test:
    usage: Erreur
    description: test

  bypass:
    usage: Erreur
    description: bypass command
